### ISSUE TITLE
Lesson 5#29 score function issue

### ISSUE THREAD

**Issue by Spikhalskiy** [udacity/aind-issue-reports#13]
In "Quiescent Search" - 29 section of "Introduction to Game Playing" by lector speech we use score function with value -1 if a computer player looses and 100 if a computer player wins.

- Before we used score function with values -1 and +1.
- In slides following after this marked values are still -1 and +1.
- Absolutely not clear what we get and what is changing with value 100 and why do we need it - looks like nothing change.

So, looks like a lecture issue and should be +1 instead of 100.

**Comment by cgearhart** [comment]
The value of 100 is intentional, however the reason for the change is not clear from the videos.

In the earlier videos, +1 indicates "win" and -1 indicates "loss"; the specific values are arbitrary. (They could be 1 and 0, or +infinity and -infinity, etc.)  In these lectures there are no intermediate values for any game state except wins and losses, so every state has only one of these two possible values.

In the video on quiescent search, the discussion has moved on to heuristic evaluation functions, which assign approximate values to non-terminal states. In that case, a loss must be the lowest possible value, and a win must be the highest possible value, but the heuristic score can be any value between those limits for non-terminal states. Specifically in those videos the heuristic can range from 0-5, so the value for a win must at least be changed from +1 to something greater than 5, and it was switched to 100 for seemingly arbitrary reasons.

It might be best to add notes or context explaining the context of the values used in the videos and why they change.

**Comment by Spikhalskiy** [comment]
I disagree.

> In the video on quiescent search, the discussion has moved on to heuristic evaluation functions, which assign approximate values to non-terminal states.

It's not true. Looking at the video:
"If we find a branch where our computer player looses, we'll give it a score of negative 1. If we find a branch where our computer player wins, we give it a score of 100".

So, we are not talking about evaluation function values here. We are talking about just marking a branch as wins or looses, as before, where we used values {-1, 1} before. And after this "100" we see slides with values {-1, +1} as before.
So, all lectures we use {-1, +1} for this specific function. After that in only one place in the video, we break this contract and mention +100 for wins. And after that, we never use this value even in this video.
So, this +100 is just a disturbing break of existing contract, which applied through all videos. And this break forcing to restart this video 5 times and asking a question - why did we decide to break existing notation and even didn't use this value at least once at least in this video.
Yes, I even moved in all these pictures with large trees after changing notation and tried to find 100 somewhere there. No, just -1 and +1 as usual.

**Comment by cgearhart** [comment]
You're correct about showing +1 on the slides, but the value _should be_ +100 (or any other value greater than 5).

Without an evaluation heuristic, every state has only a single deterministic value in the minimax tree that corresponds to either "win" or "loss" for that branch.  In a depth limited search with a heuristic, you may "guess" that a state is worth +5, only to find out in the next level of the game tree that it results in a loss (i.e., -1). Quiescent search is only meaningful when using an evaluation hueristic, because it is based on inconsistency of the evaluation due to the shifting horizon when the depth limit of search changes.

**Comment by cgearhart** [comment]
Note added to the classroom:

> [1:20] The final score of terminal board states that result in a win should be +100 in the slide rather than +1. The upper limit is arbitrary except that it must be larger than the maximum value of the evaluation heuristic, which is +5 in this case. (The value of the terminal states is defined at 0:42 of the video.)
