### ISSUE TITLE
Recognizer Project: swap x, y arctan2

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#78]
An student is reporing: the original arctan2 function takes (y, x), so I swapped them to (x, y) and it passes the unitest.

https://docs.scipy.org/doc/numpy/reference/generated/numpy.arctan2.html

Is there a bug in the test? Or an special reason for this?

**Comment by danainschool** [comment]
I'm guessing that the simple unit test is just not catching this.   As we convert Recognizer to project assistant, we'll be adding more robust tests and I am now putting this on my list - thank you!

**Comment by letyrodridc** [comment]
Hey! Dana!

Thanks. Yep, the main problem is that it's forcing students to do it wrong. 

This is inside a Python notebook. I don't know how that is going to be handled with PA.

Thanks for taking this. Cheers

**Comment by danainschool** [comment]
Do you mean that if they do it with (y,x) it fails?
no that is correct, we WANT them to swap it, because we want the discontinuity for 0 to 2pi to be at 12 'oclock rather than 3 o'clock.  The hands may move past the dicontinuity in the gestures if it is at 3 O'clock.  I think it says something about that in the notebook.

**Comment by letyrodridc** [comment]
Yes.

But I'm not quite sure if there is a good reason to use them switched. I'm not sure that is on porpuse or just a bug.

**Comment by letyrodridc** [comment]
Ok thanks I'll close the ticket than

**Comment by danainschool** [comment]
picture the gestures during sign language.  Sometimes the left hand may be as high as the nose of the person signing.  When that happens, the angle portion of the polar coordinate suddenly will jump from 0 to 2pi radians and back,etc.  When that happens, the measurement of change gets wonky because a small change looks like a giant change.  If we move that discontinuity to directly above the signer's head (12 o'clock) by switching the arctan2(y,x) to arctan2(x,y), then the discontinuity will never or hardly ever occur, because the signing does not happen above the signer's head, or at least hardly ever.  Hope this helps - I know it has been a source of confusion and a number of students have asked about that swap.

**Comment by letyrodridc** [comment]
Many thanks! I will add this information in the forum post , it's going to help future students too.
