### ISSUE TITLE
"Only Choice" order matters

### ISSUE THREAD

**Issue by letyrodridc** [udacity/aind-issue-reports#9]

**Comment by letyrodridc** [comment]
Example

Starting grid:  ..3.2.6..9..3.5..1..18.64....81.29..7.......8..67.82....26.95..8..2.3..9..5.1.3..

ORIGINAL ******************
   45    4578    3   |   49     2     147  |   6     5789    57  
   9    24678    47  |   3      47     5   |   78    278     1   
   25    257     1   |   8      79     6   |   4    23579   2357 
---------------------+---------------------+---------------------
  345    345     8   |   1     3456    2   |   9    34567  34567 
   7    123459   49  |  459   34569    4   |   1    13456    8   
  1345  13459    6   |   7     3459    8   |   2     1345   345  
---------------------+---------------------+---------------------
  134    1347    2   |   6     478     9   |   5     1478    47  
   8     1467    47  |   2     457     3   |   17    1467    9   
   46    4679    5   |   4      1      47  |   3    24678   2467 

SOLUTION ******************
  45    8     3   |  9     2     1   |  6    5789   57  
  9     6     47  |  3     4     5   |  8    278    1   
  2    257    1   |  8     7     6   |  4   23579  2357 
------------------+------------------+------------------
 345   345    8   |  1    3456   2   |  9   34567 34567 
  7     2     9   |  5   34569   4   |  1   13456   8   
 1345 13459   6   |  7    3459   8   |  2    1345  345  
------------------+------------------+------------------
 134   1347   2   |  6     8     9   |  5    1478   47  
  8    1467   47  |  2     5     3   |  17    6     9   
  6     9     5   |  4     1     7   |  3     8     2  

Looking first box A1,A2,A3, B1, B2, B3, C1, C2, C3
ORIGINAL ******************
   45    4578    3     |   
   9    24678    47  |  
   25    257     1       |  
---------------------+

SOLUTION ******************
  45    8     3     |
  9     6     47    | 
  2    257    1   |  
------------------+

A2 couldn't be an 8. It could be only if B2 is solved.... because for B2 the only option is 6. In  solution, solves B2 first.. so it puts 8 at A2.

Another comment, the solution not only analyze square unit also, column and row. In the problem explanation it only talk about square unit.  

The problem with order is that there is no other way that write the same algorithm as the solution to pass test and it's no clear the correct output.

**Comment by dhruvp** [comment]
@luisguiserrano could you please take a look at this?

**Comment by napratin** [comment]
I've resolved this issue for now by requiring students not to modify the original values, and instead modify a copy of the values, so that they get a consistent solution (see last quiz [here](https://classroom.udacity.com/nanodegrees/nd889/parts/6be67fd1-9725-4d14-b36e-ae2b5b20804c/modules/237a9d0d-e2d0-45e4-a7fd-ff4bb88203c5/lessons/b1553784-de43-42c1-a7bf-c66a6e235c47/concepts/dd16929d-4d9b-4b6a-b7ed-eb9871b4c3a1)).

This will also simplify things when they have to use search with backtracking later on. But I'd defer to you, Luis, if you have a better long-term solution in mind.

**Comment by luisguiserrano** [comment]
Thanks Arpan! Yes, that's a great solution. I'll think of something
long-term, but given that we need to check a local move (as opposed to
solving an entire sudoku, since the previous methods do it as well), this
may be the best possible solution.

On Thu, Jan 26, 2017 at 1:15 PM, Arpan Chakraborty <notifications@github.com
